Updated Spring core and Spring instrument
BroadleafCommerce/ModuleParent pull request #18
Opened 2022-11-22 14:11 UTC by MarekB01

fixes: https://github.com/BroadleafCommerce/QA/issues/4854

updated spring core to 5.3.23 and spring instrument to 5.3.23

2022-11-22 15:36 UTC, Jerry77oz approved these changes

2022-11-22 15:39 UTC, Jerry77oz requested changes, later dismissed
These changes look good but we'll also want to update the spring core from the BootStarter project: https://github.com/BroadleafCommerce/BootStarter/blob/develop-6.2.x/pom.xml#L24

2022-11-23 10:15 UTC, MarekB01 commented
> These changes look good but we'll also want to update the spring core from the BootStarter project: https://github.com/BroadleafCommerce/BootStarter/blob/develop-6.2.x/pom.xml#L24

Hi, here it is https://github.com/BroadleafCommerce/BootStarter/pull/27

2022-11-23 14:58 UTC, riteshadhikari17 approved these changes

2022-11-23 15:01 UTC, riteshadhikari17 approved these changes

2022-11-23 15:02 UTC, merged